# fly.toml app configuration file generated for apitempladavane on 2023-10-25T10:33:20-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "apitempladavane"
primary_region = "gdl"

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
